//
//  CountriesDict.swift
//  TravelDiscovery
//
//  Created by admin on 04.12.17.
//  Copyright © 2017 Jan. All rights reserved.
//

import Foundation

class CountriesDict {
    public static var Countries : Dictionary<String, String> = [
        "United States": "US",
        "Switzerland": "CH",
        "Dem. Rep. Congo": "CD",
        "San Marino": "SM",
        "Fiji": "FJ",
        "Lesotho": "LS",
        "Czech Rep.": "CZ",
        "Bolivia": "BO",
        "Maldives": "MV",
        "Sierra Leone": "SL",
        "Greece": "GR",
        "Bahrain": "BH",
        "Cyprus": "CY",
        "Kiribati": "KI",
        "Brazil": "BR",
        "French Guiana": "GF",
        "Montenegro": "ME",
        "Colombia": "CO",
        "Haiti": "HT",
        "Peru": "PE",
        "Northern Mariana Islands": "MP",
        "Seychelles": "SC",
        "Bhutan": "BT",
        "El Salvador": "SV",
        "Mauritius": "MU",
        "Gabon": "GA",
        "S. Sudan": "SS",
        "Lithuania": "LT",
        "Guinea-Bissau": "GW",
        "Ethiopia": "ET",
        "Falkland Islands": "FK",
        "Iraq": "IQ",
        "Azerbaijan": "AZ",
        "St. Helena": "SH",
        "American Samoa": "AS",
        "Cayman Islands": "KY",
        "Suriname": "SR",
        "Puerto Rico": "PR",
        "Senegal": "SN",
        "Kyrgyzstan": "KG",
        "Marshall Islands": "MH",
        "Myanmar": "MM",
        "Tokelau": "TK",
        "Venezuela": "VE",
        "South Africa": "ZA",
        "Isle of Man": "IM",
        "Zimbabwe": "ZW",
        "Clipperton Island": "CP",
        "Monaco": "MC",
        "Bulgaria": "BG",
        "Chile": "CL",
        "St. Barthélemy": "BL",
        "India": "IN",
        "Malta": "MT",
        "New Caledonia": "NC",
        "Slovenia": "SI",
        "Morocco": "MA",
        "Madagascar": "MG",
        "Mongolia": "MN",
        "Finland": "FI",
        "Anguilla": "AI",
        "Vietnam": "VN",
        "Bouvet Island": "BV",
        "Netherlands": "NL",
        "Tanzania": "TZ",
        "Albania": "AL",
        "Cuba": "CU",
        "Korea": "KR",
        "Nicaragua": "NI",
        "Norway": "NO",
        "Algeria": "DZ",
        "Sri Lanka": "LK",
        "Poland": "PL",
        "Swaziland": "SZ",
        "Lebanon": "LB",
        "São Tomé and Principe": "ST",
        "Congo": "CG",
        "So. Georgia and So. Sandwich Isl.": "GS",
        "Cape Verde": "CV",
        "Burundi": "BI",
        "Singapore": "SG",
        "Eritrea": "ER",
        "Angola": "AO",
        "Malawi": "MW",
        "Curaçao": "CW",
        "French Southern Territories": "TF",
        "Togo": "TG",
        "Åland Islands": "AX",
        "Spain": "ES",
        "Belarus": "BY",
        "Honduras": "HN",
        "Côte d’Ivoire": "CI",
        "Ecuador": "EC",
        "New Zealand": "NZ",
        "French Polynesia": "PF",
        "Caribbean Netherlands": "BQ",
        "Israel": "IL",
        "Niger": "NE",
        "Turkey": "TR",
        "Réunion": "RE",
        "Uzbekistan": "UZ",
        "Nauru": "NR",
        "Kosovo": "XK",
        "Martinique": "MQ",
        "Serbia": "RS",
        "Georgia": "GE",
        "Niue": "NU",
        "Libya": "LY",
        "Uruguay": "UY",
        "Timor-Leste": "TL",
        "Mozambique": "MZ",
        "Hungary": "HU",
        "Jordan": "JO",
        "Romania": "RO",
        "Diego Garcia": "DG",
        "Malaysia": "MY",
        "Guinea": "GN",
        "Solomon Islands": "SB",
        "Canada": "CA",
        "Botswana": "BW",
        "Belize": "BZ",
        "Chad": "TD",
        "Eq. Guinea": "GQ",
        "Egypt": "EG",
        "Comoros": "KM",
        "Guyana": "GY",
        "Estonia": "EE",
        "Barbados": "BB",
        "France": "FR",
        "Pakistan": "PK",
        "Benin": "BJ",
        "St. Kitts & Nevis": "KN",
        "Cameroon": "CM",
        "Germany": "DE",
        "Ceuta & Melilla": "EA",
        "Kazakhstan": "KZ",
        "Namibia": "NA",
        "Nigeria": "NG",
        "Gibraltar": "GI",
        "Moldova": "MD",
        "Turks and Caicos Islands": "TC",
        "Iceland": "IS",
        "British Virgin Islands": "VG",
        "St. Pierre and Miquelon": "PM",
        "Jamaica": "JM",
        "Bangladesh": "BD",
        "Japan": "JP",
        "Belgium": "BE",
        "United Arab Emirates": "AE",
        "Montserrat": "MS",
        "Slovakia": "SK",
        "Jersey": "JE",
        "Indonesia": "ID",
        "Tajikistan": "TJ",
        "U.S. Outlying Islands": "UM",
        "Canary Islands": "IC",
        "Vanuatu": "VU",
        "Liechtenstein": "LI",
        "Sweden": "SE",
        "Syria": "SY",
        "Rwanda": "RW",
        "British Indian Ocean Territory": "IO",
        "Guam": "GU",
        "Brunei": "BN",
        "Central African Rep.": "CF",
        "Trinidad and Tobago": "TT",
        "Andorra": "AD",
        "Cambodia": "KH",
        "Kuwait": "KW",
        "Tonga": "TO",
        "Aruba": "AW",
        "Micronesia": "FM",
        "Russia": "RU",
        "Liberia": "LR",
        "Christmas Island": "CX",
        "Gambia": "GM",
        "Macedonia": "MK",
        "Tunisia": "TN",
        "Wallis & Futuna": "WF",
        "Panama": "PA",
        "Bermuda": "BM",
        "Dominican Rep.": "DO",
        "Portugal": "PT",
        "Antarctica": "AQ",
        "Cook Islands": "CK",
        "Guatemala": "GT",
        "Afghanistan": "AF",
        "Western Sahara": "EH",
        "Heard and McDonald Islands": "HM",
        "Ireland": "IE",
        "Saudi Arabia": "SA",
        "Palestinian Territories": "PS",
        "Djibouti": "DJ",
        "Antigua and Barbuda": "AG",
        "United Kingdom": "GB",
        "Grenada": "GD",
        "Tristan da Cunha": "TA",
        "Macau (China)": "MO",
        "Sudan": "SD",
        "Guadeloupe": "GP",
        "Oman": "OM",
        "Tuvalu": "TV",
        "Luxembourg": "LU",
        "Mali": "ML",
        "Vatican City": "VA",
        "Somalia": "SO",
        "Hong Kong (China)": "HK",
        "Palau": "PW",
        "Dominica": "DM",
        "Croatia": "HR",
        "Thailand": "TH",
        "Philippines": "PH",
        "Papua New Guinea": "PG",
        "Mauritania": "MR",
        "St. Vincent & Grenadines": "VC",
        "Costa Rica": "CR",
        "Svalbard & Jan Mayen": "SJ",
        "Norfolk Island": "NF",
        "Iran": "IR",
        "Kenya": "KE",
        "St. Martin": "MF",
        "Ukraine": "UA",
        "Paraguay": "PY",
        "Yemen": "YE",
        "Turkmenistan": "TM",
        "Ascension Island": "AC",
        "Guernsey": "GG",
        "Cocos (Keeling) Islands": "CC",
        "Austria": "AT",
        "Greenland": "GL",
        "Bahamas": "BS",
        "Samoa": "WS",
        "Sint Maarten": "SX",
        "Italy": "IT",
        "Nepal": "NP",
        "Argentina": "AR",
        "U.S. Virgin Islands": "VI",
        "Latvia": "LV",
        "Mayotte": "YT",
        "Qatar": "QA",
        "Zambia": "ZM",
        "China": "CN",
        "St. Lucia": "LC",
        "Australia": "AU",
        "Dem. Rep. Korea": "KP",
        "Lao PDR": "LA",
        "Mexico": "MX",
        "Burkina Faso": "BF",
        "Taiwan": "TW",
        "Bosnia and Herz.": "BA",
        "Denmark": "DK",
        "Ghana": "GH",
        "Armenia": "AM",
        "Pitcairn Islands": "PN",
        "Uganda": "UG",
        "Faroe Islands": "FO"
        
    ]
  
}



