# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'TravelDiscovery' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TravelDiscovery
  pod 'FirebaseUI/Database'
  pod 'Firebase/Storage'
  
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'
  
  pod 'Mapbox-iOS-SDK', '~> 3.7'
  pod 'ScratchCard', '~> 1.1.3'
  pod 'Eureka'
  pod 'SwiftLocation', '~> 3.1.0'
  pod 'ImagePicker'
  pod 'GSMessages'
  pod 'SwiftPhotoGallery'
  
  target 'TravelDiscoveryTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
