# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'TravelDiscovery' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TravelDiscovery
  pod 'Firebase/Core'
  pod 'FirebaseUI'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Mapbox-iOS-SDK', '~> 3.7'
  pod 'ScratchCard', '~> 1.1.2'
  
  target 'TravelDiscoveryTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
